### ISSUE TITLE
Shared boundary studio updates

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1383]
As per #1235 the following features/changes are required for studio:

- [ ]  Detecting if an input file is contour. Currently the number of points in the first cell of the polydata [here](https://github.com/SCIInstitute/ShapeWorks/blob/a36280296d137a9c40034fd18a50ffa99e4803e8/Libs/Mesh/MeshWarper.cpp#L73) and [here](https://github.com/SCIInstitute/ShapeWorks/blob/a36280296d137a9c40034fd18a50ffa99e4803e8/Libs/Optimize/OptimizeParameters.cpp#L331) are checked
- [x] MeshWarp should not crash if its a contour domain. (related to #1291 ? )
- [x] Option to toggle opacity in Studio (Is this related to #1452 ?) 
- [x] Options to enable shared boundary and set the weighting across domains in studio #1780

**Comment by iyerkrithika21** [comment]
Need discuss how to include these options in the XML file?
    - Enable shared boundary and set the weighting across domains in studio  https://github.com/SCIInstitute/ShapeWorks/blob/a36280296d137a9c40034fd18a50ffa99e4803e8/Libs/Optimize/OptimizeParameters.cpp#L227
    - Option to toggle opacity in Studio. hardcoded here: https://github.com/SCIInstitute/ShapeWorks/blob/a36280296d137a9c40034fd18a50ffa99e4803e8/Libs/Optimize/OptimizeParameters.cpp#L227

**Comment by akenmorris** [comment]
My plan to support contours is to make them explicit in the spreadsheet ("contour_*"), so you would have something like this:

| shape_part1      | shape_part2 | contour_boundary|
| ----------- | ----------- | ----------- |
| 1a.vtk      | 1b.vtk       | 1boundary.vtk |
| 2a.vtk      | 2b.vtk       | 2boundary.vtk |
| 3a.vtk      | 3b.vtk       | 3boundary.vtk |

**Comment by akenmorris** [comment]
How are we generating the shared boundaries?

**Comment by iyerkrithika21** [comment]
The shared boundary is also a mesh.
So the project file has 4 input columns: left_mesh, right_mesh,shared_surface_mesh, boundary_contour.

**Comment by iyerkrithika21** [comment]
This can be a separate issue as this is related to general support for contour rather than specific to the shared boundary use case. 
> Detecting if an input file is contour. Currently the number of points in the first cell of the polydata [here](https://github.com/SCIInstitute/ShapeWorks/blob/a36280296d137a9c40034fd18a50ffa99e4803e8/Libs/Mesh/MeshWarper.cpp#L73) and [here](https://github.com/SCIInstitute/ShapeWorks/blob/a36280296d137a9c40034fd18a50ffa99e4803e8/Libs/Optimize/OptimizeParameters.cpp#L331) are checked

Closing the current issue as shared boundary studio updates were merged.
