### ISSUE TITLE
6.3 Use Case Refactoring

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1516]
Refactor use cases to:

- [x] Include mesh grooming #1386 
- [x] Pass the alignment transform to the optimizer instead of applying it #660
- [x] Use spreadsheet instead of XML #1440
- [x] Python API for the spreadsheet #1257 
- [x] Update Documentation #1720

Also related:
- [x] Combine femur use cases #1503
- [x] #1409

**Comment by jadie1** [comment]
Notes:
- Can remove center of mass alignment from grooming pipeline because reference selection no longer requires this
- Transforms need to be combined, spreadsheet can only have one grooming transform
- Default optimization should use API (need to update API to take spreadsheet input). Eventually have an interactive option to run optimization in studio 
- Analyze step should open studio

**Comment by jadie1** [comment]
Minor release for users study:
- Upgrade to new portal
- Add grooming to ellipsoid_mesh
- Update femur workflow to groom on meshes
